<script>
  import { LEFT_RIGHT_COLORING } from '$lib/constants';
  import { Skeleton } from '$lib/instructor/bouncy_instructor';
  import { SkeletonField } from '$lib/instructor/bouncy_instructor_bg';
  import Svg from '../avatar/Svg.svelte';
  import SvgAvatar from '../avatar/SvgAvatar.svelte';

  let bodyParts = [
    { name: 'Left Arm', angle: 0, isKey: false, weight: null },
    { name: 'Right Arm', angle: 0, isKey: false, weight: null },
    { name: 'Left Forearm', angle: 0, isKey: false, weight: null },
    { name: 'Right Forearm', angle: 0, isKey: false, weight: null },
    { name: 'Left Thigh', angle: 0, isKey: false, weight: null },
    { name: 'Right Thigh', angle: 0, isKey: false, weight: null },
    { name: 'Left Shin', angle: 0, isKey: false, weight: null },
    { name: 'Right Shin', angle: 0, isKey: false, weight: null },
    { name: 'Left Foot', angle: 0, isKey: false, weight: null },
    { name: 'Right Foot', angle: 0, isKey: false, weight: null },
  ];
  /** @type{Skeleton | undefined} */
  let skeleton = Skeleton.resting(false);

  /** @param {Skeleton} newSkeleton */
  export function loadSkeleton(newSkeleton) {
    // TODO(performance): these are a lot of unnecessary allocation in WASM
    bodyParts[0].angle = formatAngle(newSkeleton.left.arm.angle);
    bodyParts[1].angle = formatAngle(newSkeleton.right.arm.angle);
    bodyParts[2].angle = formatAngle(newSkeleton.left.forearm.angle);
    bodyParts[3].angle = formatAngle(newSkeleton.right.forearm.angle);
    bodyParts[4].angle = formatAngle(newSkeleton.left.thigh.angle);
    bodyParts[5].angle = formatAngle(newSkeleton.right.thigh.angle);
    bodyParts[6].angle = formatAngle(newSkeleton.left.shin.angle);
    bodyParts[7].angle = formatAngle(newSkeleton.right.shin.angle);
    bodyParts[8].angle = formatAngle(newSkeleton.left.foot.angle);
    bodyParts[9].angle = formatAngle(newSkeleton.right.foot.angle);
    skeleton = newSkeleton;
  }

  /**
   * @param {number} number
   * @returns {number}
   */
  function formatAngle(number) {
    return parseFloat(((180 * number) / Math.PI).toFixed(0));
  }

  /**
   * @param {number} number
   * @returns {number}
   */
  function toRad(number) {
    return (number * Math.PI) / 180;
  }

  function updateAvatar() {
    if (skeleton) {
      // use setter on skeleton to avoid copying intermediate objects on the
      // field getters generated by wasm bindgen
      skeleton.setAngle(SkeletonField.LeftArm, toRad(bodyParts[0].angle));
      skeleton.setAngle(SkeletonField.RightArm, toRad(bodyParts[1].angle));
      skeleton.setAngle(SkeletonField.LeftForearm, toRad(bodyParts[2].angle));
      skeleton.setAngle(SkeletonField.RightForearm, toRad(bodyParts[3].angle));
      skeleton.setAngle(SkeletonField.LeftThigh, toRad(bodyParts[4].angle));
      skeleton.setAngle(SkeletonField.RightThigh, toRad(bodyParts[5].angle));
      skeleton.setAngle(SkeletonField.LeftShin, toRad(bodyParts[6].angle));
      skeleton.setAngle(SkeletonField.RightShin, toRad(bodyParts[7].angle));
      skeleton.setAngle(SkeletonField.LeftFoot, toRad(bodyParts[8].angle));
      skeleton.setAngle(SkeletonField.RightFoot, toRad(bodyParts[9].angle));

      // trigger reactivity
      skeleton = skeleton;
    }
  }

  //   function toggleKeyPart(index) {
  //     bodyParts[index].isKey = !bodyParts[index].isKey;
  //     if (!bodyParts[index].isKey) {
  //       bodyParts[index].weight = null;
  //     }
  //   }
</script>

<div class="container">
  <div class="left input-group">
    {#each bodyParts as part, index}
      {#if index % 2 === 0}
        <div class="body-part">
          <label>{part.name}</label>
          <input
            type="number"
            class="angle-input"
            bind:value={part.angle}
            on:change={updateAvatar}
            placeholder="Angle"
          />
        </div>
      {/if}
    {/each}
  </div>

  <div class="right input-group">
    {#each bodyParts as part, index}
      {#if index % 2 === 1}
        <div class="body-part">
          <label>{part.name}</label>
          <input
            type="number"
            class="angle-input"
            bind:value={part.angle}
            on:change={updateAvatar}
            placeholder="Angle"
          />
        </div>
      {/if}
    {/each}
  </div>

  <div class="avatar">
    <Svg width={200} height={200} orderByZ>
      {#if skeleton}
        <SvgAvatar
          {skeleton}
          width={200}
          height={200}
          style={LEFT_RIGHT_COLORING}
        ></SvgAvatar>
      {/if}
    </Svg>
  </div>
</div>

<style>
  .container {
    display: grid;
    grid-template-areas:
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values';
    gap: 8px;
    justify-items: center;
  }
  .left {
    grid-area: left-values;
    background-color: var(--theme-accent-light);
  }
  .right {
    grid-area: right-values;
    background-color: var(--theme-neutral-light);
  }
  .avatar {
    grid-area: avatar;
  }
  .input-group {
    padding: 5px;
  }
  .body-part {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 90%;
    margin: auto;
  }
  .angle-input {
    width: 100%;
    text-align: center;
  }

  @media (max-width: 600px) {
    .container {
      grid-template-areas:
        'avatar avatar'
        'right-values left-values';
    }
  }
</style>
