<script>
  import { LEFT_RIGHT_COLORING } from '$lib/constants';
  import { t } from '$lib/i18n';
  import {
    PoseWrapper,
    Skeleton,
    SkeletonWrapper,
  } from '$lib/instructor/bouncy_instructor';
  import { SkeletonField } from '$lib/instructor/bouncy_instructor_bg';
  import Svg from '../avatar/Svg.svelte';
  import SvgAvatar from '../avatar/SvgAvatar.svelte';
  import AngleInput from '../ui/AngleInput.svelte';
  import Button from '../ui/Button.svelte';

  let bodyParts = [
    { name: 'editor.body.arm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.arm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.forearm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.forearm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.thigh', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.thigh', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.shin', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.shin', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.foot', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.foot', angle: 0, isKey: false, weight: null },
  ];
  /** @type{Skeleton | undefined} */
  let skeleton = Skeleton.resting(false);
  /** @type{PoseWrapper | undefined} */
  let pose;

  /** @param {PoseWrapper} pose */
  export let onChange = (pose) => {};

  /** @param {SkeletonWrapper} inputSkeleton */
  export function loadSkeleton(inputSkeleton) {
    loadPose(inputSkeleton.pose());
  }

  /** @param {PoseWrapper} inputPose */
  export function loadPose(inputPose) {
    pose = inputPose;
    updateAnglesFromPose(pose);
  }

  /** @returns {PoseWrapper | undefined} */
  export function readPose() {
    return pose;
  }

  function updateAnglesFromPose(pose) {
    skeleton = pose.skeleton();

    bodyParts[0].angle = pose.getAngle(SkeletonField.LeftArm) - 90.0;
    bodyParts[1].angle = pose.getAngle(SkeletonField.RightArm) - 90.0;
    bodyParts[2].angle = pose.getAngle(SkeletonField.LeftForearm) - 90.0;
    bodyParts[3].angle = pose.getAngle(SkeletonField.RightForearm) - 90.0;
    bodyParts[4].angle = pose.getAngle(SkeletonField.LeftThigh) - 90.0;
    bodyParts[5].angle = pose.getAngle(SkeletonField.RightThigh) - 90.0;
    bodyParts[6].angle = pose.getAngle(SkeletonField.LeftShin) - 90.0;
    bodyParts[7].angle = pose.getAngle(SkeletonField.RightShin) - 90.0;
    bodyParts[8].angle = pose.getAngle(SkeletonField.LeftFoot) - 90.0;
    bodyParts[9].angle = pose.getAngle(SkeletonField.RightFoot) - 90.0;
  }

  function updateAvatar() {
    if (pose) {
      // use setter on skeleton to avoid copying intermediate objects on the
      // field getters generated by wasm bindgen
      pose.setAngle(SkeletonField.LeftArm, bodyParts[0].angle);
      pose.setAngle(SkeletonField.RightArm, bodyParts[1].angle);
      pose.setAngle(SkeletonField.LeftForearm, bodyParts[2].angle);
      pose.setAngle(SkeletonField.RightForearm, bodyParts[3].angle);
      pose.setAngle(SkeletonField.LeftThigh, bodyParts[4].angle);
      pose.setAngle(SkeletonField.RightThigh, bodyParts[5].angle);
      pose.setAngle(SkeletonField.LeftShin, bodyParts[6].angle);
      pose.setAngle(SkeletonField.RightShin, bodyParts[7].angle);
      pose.setAngle(SkeletonField.LeftFoot, bodyParts[8].angle);
      pose.setAngle(SkeletonField.RightFoot, bodyParts[9].angle);

      updateSkeleton();
    }
  }

  function updateSkeleton() {
    if (pose) {
      skeleton = pose.skeleton();
      onChange(pose);
    }
  }
</script>

<div class="container">
  <div class="left input-group">
    {#each bodyParts as part, index}
      {#if index % 2 === 0}
        <div class="body-part">
          <label for="left-{index}">{$t(part.name)}</label>
          <AngleInput
            name="left-{index}"
            bind:value={part.angle}
            onChange={updateAvatar}
          ></AngleInput>
        </div>
      {/if}
    {/each}
  </div>

  <div class="right input-group">
    {#each bodyParts as part, index}
      {#if index % 2 === 1}
        <div class="body-part">
          <label for="right-{index}">{$t(part.name)}</label>
          <AngleInput
            name="right-{index}"
            bind:value={part.angle}
            onChange={updateAvatar}
          ></AngleInput>
        </div>
      {/if}
    {/each}
  </div>

  <div class="avatar">
    <Svg width={200} height={200} orderByZ>
      {#if skeleton}
        <SvgAvatar
          {skeleton}
          width={200}
          height={200}
          style={LEFT_RIGHT_COLORING}
        ></SvgAvatar>
      {/if}
    </Svg>
  </div>

  {#if pose}
    <div class="direction">
      <!-- {PoseDirection[pose?.direction]} -->
      <Button
        class="light short"
        symbolSize={29}
        symbol="sync"
        on:click={() => {
          pose.setDirection((pose.direction + 1) % 2);
          updateSkeleton();
        }}
      ></Button>
    </div>

    <div class="body-turn">
      <div class="turn">
        <label for="turn-shoulder">{$t('editor.body.shoulder')}</label>
        <input
          name="turn-shoulder"
          type="number"
          class="turn-input angle-input"
          bind:value={pose.turnShoulder}
          on:change={updateSkeleton}
          placeholder={$t('editor.body.shoulder')}
          min={-45}
          max={45}
        />
      </div>

      <div class="turn">
        <label for="turn-hip">{$t('editor.body.hip')}</label>
        <input
          name="turn-hip"
          type="number"
          class="turn-input angle-input"
          bind:value={pose.turnHip}
          on:change={updateSkeleton}
          placeholder={$t('editor.body.hip')}
          min={-45}
          max={45}
        />
      </div>
    </div>
  {/if}
</div>

<style>
  .container {
    display: grid;
    grid-template-areas:
      'right-values direction left-values'
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values body-turn left-values';
    gap: 8px;
    justify-items: center;
  }
  .left {
    grid-area: left-values;
  }
  .right {
    grid-area: right-values;
  }
  .avatar {
    grid-area: avatar;
  }
  .direction {
    grid-area: direction;
  }
  .body-turn {
    grid-area: body-turn;
  }
  .input-group {
    padding: 5px;
    width: 90%;
  }
  .body-part {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 90%;
    margin: 5px auto;
    padding: 10px 5px;
  }
  .left .body-part {
    background-color: var(--theme-accent-light);
  }
  .right .body-part {
    background-color: var(--theme-neutral-light);
  }
  .angle-input {
    width: 100%;
    text-align: center;
  }
  .turn-input {
    font-size: 20px;
  }
  .body-turn {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
    margin: 10px;
  }

  @media (max-width: 600px) {
    .container {
      grid-template-areas:
        'direction direction'
        'body-turn body-turn'
        'avatar avatar'
        'right-values left-values';
    }
  }
</style>
