<script>
  import { LEFT_RIGHT_COLORING } from '$lib/constants';
  import { t } from '$lib/i18n';
  import {
    PoseWrapper,
    Skeleton,
    SkeletonWrapper,
  } from '$lib/instructor/bouncy_instructor';
  import { SkeletonField } from '$lib/instructor/bouncy_instructor_bg';
  import Svg from '../avatar/Svg.svelte';
  import SvgAvatar from '../avatar/SvgAvatar.svelte';

  let bodyParts = [
    { name: 'editor.body.arm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.arm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.forearm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.forearm', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.thigh', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.thigh', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.shin', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.shin', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.foot', angle: 0, isKey: false, weight: null },
    { name: 'editor.body.foot', angle: 0, isKey: false, weight: null },
  ];
  /** @type{Skeleton | undefined} */
  let skeleton = Skeleton.resting(false);
  /** @type{PoseWrapper | undefined} */
  let pose;

  /** @param {SkeletonWrapper} newSkeleton */
  export function loadSkeleton(newSkeleton) {
    pose = newSkeleton.pose();
    skeleton = pose.skeleton();

    bodyParts[0].angle = pose.getAngle(SkeletonField.LeftArm);
    bodyParts[1].angle = pose.getAngle(SkeletonField.RightArm);
    bodyParts[2].angle = pose.getAngle(SkeletonField.LeftForearm);
    bodyParts[3].angle = pose.getAngle(SkeletonField.RightForearm);
    bodyParts[4].angle = pose.getAngle(SkeletonField.LeftThigh);
    bodyParts[5].angle = pose.getAngle(SkeletonField.RightThigh);
    bodyParts[6].angle = pose.getAngle(SkeletonField.LeftShin);
    bodyParts[7].angle = pose.getAngle(SkeletonField.RightShin);
    bodyParts[8].angle = pose.getAngle(SkeletonField.LeftFoot);
    bodyParts[9].angle = pose.getAngle(SkeletonField.RightFoot);
  }

  /** @returns {PoseWrapper | undefined} */
  export function readPose() {
    return pose;
  }

  function updateAvatar() {
    if (pose) {
      // use setter on skeleton to avoid copying intermediate objects on the
      // field getters generated by wasm bindgen
      pose.setAngle(SkeletonField.LeftArm, bodyParts[0].angle);
      pose.setAngle(SkeletonField.RightArm, bodyParts[1].angle);
      pose.setAngle(SkeletonField.LeftForearm, bodyParts[2].angle);
      pose.setAngle(SkeletonField.RightForearm, bodyParts[3].angle);
      pose.setAngle(SkeletonField.LeftThigh, bodyParts[4].angle);
      pose.setAngle(SkeletonField.RightThigh, bodyParts[5].angle);
      pose.setAngle(SkeletonField.LeftShin, bodyParts[6].angle);
      pose.setAngle(SkeletonField.RightShin, bodyParts[7].angle);
      pose.setAngle(SkeletonField.LeftFoot, bodyParts[8].angle);
      pose.setAngle(SkeletonField.RightFoot, bodyParts[9].angle);

      skeleton = pose.skeleton();
    }
  }
</script>

<div class="container">
  <div class="left input-group">
    {#each bodyParts as part, index}
      {#if index % 2 === 0}
        <div class="body-part">
          <label for="left-{index}">{$t(part.name)}</label>
          <input
            name="left-{index}"
            type="number"
            class="angle-input"
            bind:value={part.angle}
            on:change={updateAvatar}
            placeholder="Angle"
          />
        </div>
      {/if}
    {/each}
  </div>

  <div class="right input-group">
    {#each bodyParts as part, index}
      {#if index % 2 === 1}
        <div class="body-part">
          <label for="right-{index}">{$t(part.name)}</label>
          <input
            name="right-{index}"
            type="number"
            class="angle-input"
            bind:value={part.angle}
            on:change={updateAvatar}
            placeholder="Angle"
          />
        </div>
      {/if}
    {/each}
  </div>

  <div class="avatar">
    <Svg width={200} height={200} orderByZ>
      {#if skeleton}
        <SvgAvatar
          {skeleton}
          width={200}
          height={200}
          style={LEFT_RIGHT_COLORING}
        ></SvgAvatar>
      {/if}
    </Svg>
  </div>
</div>

<style>
  .container {
    display: grid;
    grid-template-areas:
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values'
      'right-values avatar left-values';
    gap: 8px;
    justify-items: center;
  }
  .left {
    grid-area: left-values;
    background-color: var(--theme-accent-light);
  }
  .right {
    grid-area: right-values;
    background-color: var(--theme-neutral-light);
  }
  .avatar {
    grid-area: avatar;
  }
  .input-group {
    padding: 5px;
  }
  .body-part {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 90%;
    margin: auto;
  }
  .angle-input {
    width: 100%;
    text-align: center;
  }

  @media (max-width: 600px) {
    .container {
      grid-template-areas:
        'avatar avatar'
        'right-values left-values';
    }
  }
</style>
