version: "3.6"
services:
  bouncy_stats:
    image: bouncy_stats
    build:
      context: ./
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - data:/app/db.sqlite
    ports:
      - 3000:3000
volumes:
    data:
        external: false
