version: "3.6"
services:
  bouncy_stats:
    image: jakmeier/bouncy-feet:bouncy_stats
    environment:
      CLIENT_URL: https://app.bouncy-feet.ch
      API_URL: https://stats.bouncy-feet.ch
      OIDC_ISSUER: https://auth.bouncy-feet.ch/realms/bouncyfeet
      OIDC_CLIENT_SECRET: XXXX
      OIDC_CLIENT_ID: bouncy-backend
    volumes:
      - data:/app/db.sqlite
    ports:
      - 3002:3000
    restart: always
volumes:
    data:
        external: false
