version: "3.6"
services:
  bouncy_stats:
    image: bouncy_stats
    environment:
      CLIENT_URL: http://localhost:5173
      API_URL: http://localhost:3000
      OIDC_ISSUER: https://auth.bouncy-feet.ch/realms/bouncyfeet-dev
      OIDC_CLIENT_SECRET: XXXX
      OIDC_CLIENT_ID: bouncy-dev-backend
      DATABASE_URL: "postgres://api_user:local_password@postgres/bouncyfeet"
    build:
      context: ./
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - data:/app/db.sqlite
    ports:
      - 3000:3000
    networks:
      - local_network
  postgres:
    image: postgres:17.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bouncyfeet
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: local_password
    ports:
      - 65432:5432
    networks:
      - local_network
    restart: always
volumes:
  data:
    external: false
  pgdata:
networks:
  local_network:
    driver: bridge