name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  bouncy_instructor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      working-directory: ./bouncy_instructor
      run: cargo clippy --all-targets --all-features
    - name: Build
      working-directory: ./bouncy_instructor
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./bouncy_instructor
      run: cargo test --verbose

  bouncy_stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      working-directory: ./bouncy_stats
      run: cargo clippy --all-targets --all-features
    - name: Build
      working-directory: ./bouncy_stats
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./bouncy_stats
      run: cargo test --verbose
